version: '3'

services:
  app:
    container_name: bank_service
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes: 
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lozik@tambler.ru
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - 80:80
    restart: always

  migration:
    container_name: migration
    build:
      context: .
    command:
      [
        "npx",
        "sequelize-cli",
        "db:migrate"
      ]
    links:
      - db
    depends_on:
      - db
    env_file: ./.env
  seed:
    container_name: seed
    build:
      context: .
    command:
      [
        "npx",
        "sequelize-cli",
        "db:seed:all"
      ]
    links:
      - db
    depends_on:
      - db
      - migration
    env_file: ./.env

volumes:
  db:
    driver: local